services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./db.env
      - ./db_sec.env

  web:
    image: golang:latest
    working_dir: /app
    command: go run app.go
    volumes:
      - ./web:/app
    ports:
      - "58080:80"
    depends_on:
      - db
    env_file:
      - ./db.env
      - ./db_sec.env

volumes:
  db_data:
